config/routes.rb
TurbolinkTransitions::Application.routes.draw do
  root "transitions#index"
  get '/:id' => 'transitions#index', as: :transition_demo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def index
    
  end
  
end

app/controllers/transitions_controller.rb
class TransitionsController < ApplicationController
  def index
    if params[:id]
      # generate a layout based on the integer passed in on the url
      @id = params[:id].to_i
      @max_col = (@id % 3) + 1
      @col = 12 / @max_col
      @row = (@id / 6) + 1
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sam_jackson_says
    [
      "You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man.",
      "Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.",
      "Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'?",
      "Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass.",
      "Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing.",
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?",
      "Now that there is the Tec-9, a crappy spray gun from South Miami. This gun is advertised as the most popular gun in American crime. Do you believe that shit? It actually says that in the little book that comes with it: the most popular gun in American crime. Like they're actually proud of that shit. "
    ].sample
  end
  
end

app/helpers/transitions_helper.rb
module TransitionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div class="previous content">
    </div>
    <div class="current content">
      <%= yield %>
    </div>
    <footer class="row full-width"></footer>
  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name"><h1><%= link_to "Turbolink Transitions", :root %></h1></li>
  </ul>
  <section class="top-bar-section">
    <ul>
      <li><%= link_to "Transition Demo", transition_demo_path(rand(100)) %></li>
    </ul>
  </section>
</nav>

app/views/transitions/_sam_jackson_copy.html.erb
<% @row.times do |r| %>
<div class="row"> <!-- // ROW -->    
  <% @max_col.times do |c| %>  
  <div class="large-<%= @col %> columns"> <!-- // Column span <%= @col %> -->
    <p><%= sam_jackson_says %></p>
  </div> <!-- // END Column span <%= @col %> -->
  <% end %>
  <hr>
</div> <!-- // END ROW -->
<% end %>

app/views/transitions/index.html.erb
<div class="row"> <!-- // ROW -->
  <div class="large-12 columns"> <!-- // Column span 12 -->
    <h1>Transitions#index <small><%= @id %></small></h1>
  </div> <!-- // END Column span 12 -->
</div> <!-- // END ROW -->

<% if @id %>
  <%= render 'transitions/sam_jackson_copy' %>
<% else %>
    <div class="row"> <!-- // ROW -->
      <p>Demo of steps required to have full transitions for pages between turbo link events</p>
    </div> <!-- // END ROW -->
<% end %>